CREATE DATABASE MOVIES05062005
ON PRIMARY
(NAME = MOVIES05062005_data, FILENAME = 'D:\CSDL\BTCSDL_T2\MOVIES05062005_data.mdf', SIZE = 25MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
LOG ON
(NAME = MOVIES05062005_log, FILENAME = 'D:\CSDL\BTCSDL_T2\MOVIES05062005_log.ldf', SIZE = 6MB, MAXSIZE = 8MB, FILEGROWTH = 1MB);
ALTER DATABASE MOVIES05062005 ADD FILE ( NAME = MOVIES2_data2, FILENAME = 'D:\CSDL\BTCSDL_T2\MOVIES05062005_data2.ndf', SIZE = 10MB);
ALTER DATABASE MOVIES2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
SELECT name, user_access_desc FROM sys.databases WHERE name = 'MOVIES05062005';
ALTER DATABASE MOVIES2 SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE;
SELECT name, user_access_desc FROM sys.databases WHERE name = 'MOVIES05062005';
ALTER DATABASE MOVIES2 SET multi_user WITH ROLLBACK IMMEDIATE;

SELECT name, user_access_desc FROM sys.databases WHERE name = 'MOVIES05062005';
ALTER DATABASE MOVIES05062005 MODIFY FILE (NAME = MOVIES2_data2, SIZE = 15MB);

EXEC sp_helpdb MOVIES05062005;

ALTER DATABASE MOVIES2 SET AUTO_SHRINK ON;
SELECT name, is_auto_shrink_on FROM sys.databases WHERE name = 'MOVIES05062005';

CREATE DATABASE [MOVIES05062005]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MOVIES1', FILENAME = N'D:\CSDL\BTCSDL_T2\MOVIES1.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MOVIES1_log', FILENAME = N'D:\CSDL\BTCSDL_T2\MOVIES1_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MOVIES1] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MOVIES1].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE MOVIES05062005 ADD FILEGROUP DATA;
ALTER DATABASE MOVIES05062005 MODIFY FILE ( NAME = MOVIES05062005_log, MAXSIZE = 10MB);
ALTER DATABASE MOVIES05062005 MODIFY FILE (NAME = MOVIES_data2, SIZE = 10MB);
ALTER DATABASE MOVIES05062005 MODIFY FILE (NAME = MOVIES05062005_data2, FILEGROUP = DATA);
EXEC sp_helpDB MOVIES05062005;

CREATE TYPE Movie_num FROM INT NOT NULL;
CREATE TYPE Category_num FROM INT NOT NULL;
CREATE TYPE Cust_num FROM INT NOT NULL;
CREATE TYPE Invoice_num FROM INT NOT NULL;

CREATE TABLE Customer( Cust_num INT IDENTITY(300,1) NOT NULL,
	Lname VARCHAR(20) NOT NULL,
	Fname VARCHAR(20)NOT NULL,
	Address1 VARCHAR(30),
	Address2 VARCHAR(20),
	City VARCHAR(20),
	State CHAR(2),
	Zip CHAR(10),
	Phone VARCHAR(10) NOT NULL,
	Join_date SMALLDATETIME NOT NULL);
CREATE TABLE Category( Category_num INT IDENTITY(1,1) NOT NULL,
	Description VARCHAR(20) NOT NULL);
CREATE TABLE Movie (Movie_num INT NOT NULL,
	Title NVARCHAR(30) NOT NULL,
	Category_Num INT NOT NULL,
	Date_purch Smalldatetime,
	Rental_price Int,
	Rating Char(5));
CREATE TABLE Rental (Invoice_num INT NOT NULL,
	Cust_num INT NOT NULL,
	Rental_date SMALLDATETIME NOT NULL,
	Due_date SMALLDATETIME NOT NULL);
CREATE TABLE Rental_detail (Invoice_num INT NOT NULL,
	Line_num INT NOT NULL,
	Movie_num INT NOT NULL,
	Rental_price SMALLMONEY NOT NULL);
CREATE DATABASE [MOVIES1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MOVIES1', FILENAME = N'D:\CSDL\BTCSDL_T2\MOVIES1.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MOVIES1_log', FILENAME = N'D:\CSDL\BTCSDL_T2\MOVIES1_log.ldf' , SIZE = 1024KB , MAXSIZE = 10240KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MOVIES1] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MOVIES1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MOVIES1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MOVIES1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MOVIES1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MOVIES1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MOVIES1] SET ARITHABORT OFF 
GO

ALTER DATABASE [MOVIES1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MOVIES1] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MOVIES1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MOVIES1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MOVIES1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MOVIES1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MOVIES1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MOVIES1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MOVIES1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MOVIES1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MOVIES1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MOVIES1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MOVIES1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MOVIES1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MOVIES1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MOVIES1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MOVIES1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MOVIES1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MOVIES1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MOVIES1] SET  MULTI_USER 
GO

ALTER DATABASE [MOVIES1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MOVIES1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MOVIES1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MOVIES1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MOVIES1] SET  READ_WRITE 
GO

ALTER TABLE Movie ADD CONSTRAINT PK_Movie PRIMARY KEY (Movie_num);
ALTER TABLE Customer ADD CONSTRAINT PK_Customer PRIMARY KEY (Cust_num);
ALTER TABLE Category ADD CONSTRAINT PK_Category PRIMARY KEY (Category_num);
ALTER TABLE Rental ADD CONSTRAINT PK_Rental PRIMARY KEY (Invoice_num);

ALTER TABLE Movie ADD CONSTRAINT FK_Movie_Category FOREIGN KEY (Category_num) REFERENCES Category (Category_num);
ALTER TABLE Rental ADD CONSTRAINT FK_Rental_Customer FOREIGN KEY (Cust_num) REFERENCES Customer (Cust_num);
ALTER TABLE Rental_detail ADD CONSTRAINT FK_Rental_detail_Rental FOREIGN KEY (Invoice_num) REFERENCES Rental (Invoice_num);
ALTER TABLE Rental_detail ADD CONSTRAINT FK_Rental_detail_Movie FOREIGN KEY (Movie_num) REFERENCES Movie (Movie_num);

ALTER TABLE Movie  ADD CONSTRAINT DK_movie_date_purch DEFAULT GETDATE() FOR Date_purch;
ALTER TABLE Customer ADD CONSTRAINT DK_customer_join_date DEFAULT GETDATE() FOR Join_date;
ALTER TABLE Rental ADD CONSTRAINT DK_rental_rental_date DEFAULT GETDATE() FOR Rental_date;
ALTER TABLE Rental ADD CONSTRAINT DK_rental_due_date DEFAULT DATEADD(day, 2, GETDATE()) FOR Due_date;

EXEC sp_helpconstraint Movie;
EXEC sp_helpconstraint Customer;
EXEC sp_helpconstraint Rental;

ALTER TABLE Movie ADD CONSTRAINT CK_Rating CHECK (Rating IN ('G', 'PG', 'R', 'NC17', 'NR'));
ALTER TABLE Rental ADD CONSTRAINT CK_Due_date CHECK (Due_date > Rental_date);
EXEC sp_helpconstraint Movie;
EXEC sp_helpconstraint Rental;